#The following imports will call the endpoints of discord. Then, the __init__.py from /frameworks_and_drivers will call this script, linking the endpoints to the main.py file.

#Events
from project.frameworks_and_drivers.discord_bot.controller.events_controller.infra_event import on_ready
from project.frameworks_and_drivers.discord_bot.controller.events_controller.bot_joined_server_event import on_guild_join
from project.frameworks_and_drivers.discord_bot.controller.events_controller.new_message_event import on_message
from project.frameworks_and_drivers.discord_bot.controller.events_controller.new_member_event import on_member_join
from project.frameworks_and_drivers.discord_bot.controller.events_controller.new_channel_event import on_guild_channel_create
from project.frameworks_and_drivers.discord_bot.controller.events_controller.rm_msg_event import on_raw_message_delete
from project.frameworks_and_drivers.discord_bot.controller.events_controller.update_msg_event import on_raw_message_edit
from project.frameworks_and_drivers.discord_bot.controller.events_controller.rm_member_event import on_member_remove
from project.frameworks_and_drivers.discord_bot.controller.events_controller.rm_channel_event import on_guild_channel_delete
from project.frameworks_and_drivers.discord_bot.controller.events_controller.update_channel_event import on_guild_channel_update

#Commands
from project.frameworks_and_drivers.discord_bot.controller.commands_controller.get_report_members import get_report_members
from project.frameworks_and_drivers.discord_bot.controller.commands_controller.predict_members_qtt import predict_members_qtt
from project.frameworks_and_drivers.discord_bot.controller.commands_controller.get_prob_new_members import get_prob_new_members
from project.frameworks_and_drivers.discord_bot.controller.commands_controller.get_top_active_channels import get_top_active_channels
from project.frameworks_and_drivers.discord_bot.controller.commands_controller.get_ch_metrics import get_channel_metrics