# syntax=docker/dockerfile:1

FROM python:3.13-slim

WORKDIR /feed

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY ./project ./project
COPY ./feed ./feed

CMD ["python", "./feed/feed.py"]